// src/react/components/Benchmark.tsx
import React, { useState } from 'react';

import { measureRenderTime } from '../../common/components/benchmark';

import { useBenchmarkStore } from '../store/benchmarkStore';

export default function Counter() {
    const _divList = useBenchmarkStore(state => state.divList);
    const add = useBenchmarkStore(state => state.addRandomColorDiv);
    const empty = useBenchmarkStore(state => state.emptyRandomColorDiv);
    const [count, setCount] = useState(0);
    const [duration, setDuration] = useState(0);

    function _add(count: number) {
        add(count);
    }

    function _render() {
        measureRenderTime(_add, count, setDuration);
    }

    function handleNumberInput(event: React.ChangeEvent<HTMLInputElement>) {
        setCount(parseInt(event.target.value));
    }
    return (
        <React.Fragment>
            <div className='block'>
                <div className='subtitle is-2 header-framework-test-react'>Benchmark, Spend Time: {duration} ms</div>

                <div className='field'>
                    <label className='label'>Render Number</label>
                    <div className='control'>
                        <input type='number' className='input' placeholder='Render Number' value={count} onChange={handleNumberInput} />
                    </div>
                </div>

                <div className='field is-grouped'>
                    <div className='control'>
                        <button className='button is-large button-framework-test-react' onClick={_render}>
                            Render
                        </button>
                    </div>
                    <div className='control'>
                        <button className='button is-large button-framework-test-react' onClick={empty}>
                            Empty
                        </button>
                    </div>
                </div>

                <div className='columns is-multiline'>
                    {_divList.map(ds => {
                        return (
                            <div key={ds.id} className='column is-1' style={{ backgroundColor: ds.backgroundColor, color: ds.color, fontSize: '8px' }}>
                                Div# {ds.id}
                            </div>
                        );
                    })}
                </div>
            </div>
        </React.Fragment>
    );
}

// src/svelte/components/Benchmark.svelte
<script lang="ts">
    import { divList, addRandomColorDiv, emptyRandomColorDiv } from '../store/benchmarkStore';
    import { measureRenderTime } from '../../common/components/benchmark';
    let count = $state(0);
    let duration = $state(0);

    function handleNumberInput(event: Event) {
        const input = event.target as HTMLInputElement;
        count = parseInt(input.value);
    }

    function _updateDuration(time: number) {
        duration = time;
    }

    async function _render() {
        measureRenderTime(addRandomColorDiv, count, _updateDuration);
    }
</script>

<div class="block">
    <div class="subtitle is-2 header-framework-test-svelte">Benchmark, Spend Time: {duration} ms</div>

    <div class="field">
        <!-- svelte-ignore a11y_label_has_associated_control -->
        <label class="label">Render Number</label>
        <div class="control">
            <input type="number" class="input" placeholder="Render Number" bind:value={count} oninput={handleNumberInput} />
        </div>
    </div>

    <div class="field is-grouped">
        <div class="control">
            <button class="button is-large button-framework-test-svelte" onclick={_render}>Render</button>
        </div>
        <div class="control">
            <button class="button is-large button-framework-test-svelte" onclick={emptyRandomColorDiv}>Empty</button>
        </div>
    </div>

    <div class="columns is-multiline">
        {#each $divList as ds (ds.id)}
            <div class="column is-1" style="background-color: {ds.backgroundColor}; color: {ds.color}; font-size: 8px;">Div# {ds.id}</div>
        {/each}
    </div>
</div>
