// src/react/App.tsx
import './app.css';

import React, { useState } from 'react';
import Modal from './components/Modal';

import reactLogo from '../assets/svg/react.svg';

import { useShowStore } from './store/showStore';

export default function App() {
    const [focus, setFocus] = useState(false);

    const _show = useShowStore(state => state.show);
    const _open = useShowStore(state => state.open);
    return (
        <React.Fragment>
            <button id='framework-test-react-modal' className='button framework-test-modal-switch' onClick={_open} onMouseEnter={() => setFocus(true)} onMouseLeave={() => setFocus(false)}>
                {focus && <span>More</span>}
                <img src={reactLogo} className='ft-button-logo' alt='React logo' />
            </button>
            {_show && <Modal msg='Welcome React'></Modal>}
        </React.Fragment>
    );
}

// src/solid/App.tsx
import './app.css';
import { createSignal } from 'solid-js';
import { Show } from 'solid-js';
import solidLogo from '../assets/svg/solid.svg';

import Modal from './components/Modal';

import { show, open } from './signal/showSignal';

function App() {
    const [focus, setFocus] = createSignal(false);

    return (
        <div>
            <button id='framework-test-solid-modal' class='button framework-test-modal-switch' onClick={open} onMouseEnter={() => setFocus(true)} onMouseLeave={() => setFocus(false)}>
                {focus() && <span>More</span>}
                <img src={solidLogo} class='ft-button-logo' alt='Solid logo' />
            </button>
            <Show when={show()}>
                <Modal msg='Welcome Solid' />
            </Show>
        </div>
    );
}

export default App;
