// src/preact/App.tsx
import './app.css';

import { Fragment } from 'preact';
import { useState } from 'preact/hooks';

import preactLogo from '../assets/svg/preact.svg';

import Modal from './components/Modal';

import { show, open } from './signal/showSignal';

export function App() {
    const _show = show.value;
    const [focus, setFocus] = useState(false);

    return (
        <Fragment>
            <button id='framework-test-preact-modal' class='button framework-test-modal-switch' onClick={open} onMouseEnter={() => setFocus(true)} onMouseLeave={() => setFocus(false)}>
                {focus && <span>More</span>}
                <img src={preactLogo} class='ft-button-logo' alt='Preact logo' />
            </button>
            {_show && <Modal msg='Welcome Preact'></Modal>}
        </Fragment>
    );
}

// src/solid/App.tsx
import './app.css';
import { createSignal } from 'solid-js';
import { Show } from 'solid-js';
import solidLogo from '../assets/svg/solid.svg';

import Modal from './components/Modal';

import { show, open } from './signal/showSignal';

function App() {
    const [focus, setFocus] = createSignal(false);

    return (
        <div>
            <button id='framework-test-solid-modal' class='button framework-test-modal-switch' onClick={open} onMouseEnter={() => setFocus(true)} onMouseLeave={() => setFocus(false)}>
                {focus() && <span>More</span>}
                <img src={solidLogo} class='ft-button-logo' alt='Solid logo' />
            </button>
            <Show when={show()}>
                <Modal msg='Welcome Solid' />
            </Show>
        </div>
    );
}

export default App;
